-- MabuhAi — schema bootstrap
--
-- This file is kept for backward compatibility with the original "paste a
-- single file in the Supabase SQL editor" workflow. The actual schema now
-- lives in versioned, non-destructive migrations:
--
--   supabase/migrations/0001_migration_table.sql
--   supabase/migrations/0002_profiles.sql
--   supabase/migrations/0003_auth_lifecycle.sql
--   supabase/migrations/0004_mood_entries.sql
--   supabase/migrations/0005_journal_entries.sql
--   supabase/migrations/0006_journey_progress.sql
--   supabase/migrations/0007_journey_garden_mode.sql
--   supabase/migrations/0008_delete_user_data.sql
--
-- For a fresh database, the recommended path is the Supabase CLI:
--
--   supabase db push
--
-- For an existing database that was previously bootstrapped with the
-- monolithic schema, run the same `supabase db push` — the migrations are
-- idempotent (every CREATE uses `if not exists`, every POLICY is dropped
-- and recreated) and they do NOT drop or destroy any user data.
--
-- If you want to keep using the SQL editor instead of the CLI, run each
-- migration file in order. The Supabase CLI's schema_migrations table will
-- not be updated by the editor, so the next `supabase db push` will try
-- to re-apply everything; that's safe because every statement is
-- idempotent, but you can also record them manually:
--
--   insert into supabase_migrations.schema_migrations(version, name)
--   values
--     ('0001', 'migration_table'),
--     ('0002', 'profiles'),
--     ('0003', 'auth_lifecycle'),
--     ('0004', 'mood_entries'),
--     ('0005', 'journal_entries'),
--     ('0006', 'journey_progress'),
--     ('0007', 'journey_garden_mode'),
--     ('0008', 'delete_user_data');
--
-- This file is intentionally a no-op so re-running it does nothing harmful.
select 1;
