import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#111113",
  },
  themeSunrise: {
    backgroundColor: "#20130b",
  },
  themeTerminal: {
    backgroundColor: "#0f1712",
  },
  skyGlowTop: {
    position: "absolute",
    top: -80,
    right: -50,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: "rgba(255, 138, 29, 0.12)",
  },
  skyGlowBottom: {
    position: "absolute",
    left: -60,
    bottom: 90,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: "rgba(170, 170, 170, 0.08)",
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 34,
    paddingBottom: 120,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandMenuWrap: {
    position: "relative",
  },
  menuButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
  },
  hamburgerLine: {
    width: 18,
    height: 2,
    borderRadius: 999,
    backgroundColor: "#ffb347",
  },
  brandDropdown: {
    position: "absolute",
    top: 44,
    left: 0,
    zIndex: 30,
    minWidth: 150,
    padding: 8,
    borderRadius: 14,
    backgroundColor: "rgba(31, 31, 35, 0.98)",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.28)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 8,
  },
  brandDropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  brandDropdownItemActive: {
    backgroundColor: "rgba(255, 138, 29, 0.14)",
  },
  brandDropdownText: {
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "800",
  },
  brandDropdownTextActive: {
    color: "#f2f2f2",
  },

  movingPlane: {
    position: "absolute",
    top: 180,
    left: 20,
    zIndex: 999,
  },

  flightBanner: {
    backgroundColor: "rgba(255, 138, 29,0.15)",
    borderWidth: 1,
    borderColor: "#ff8a1d",
    padding: 10,
    borderRadius: 12,
    marginBottom: 10,
    alignItems: "center",
  },

  flightBannerText: {
    color: "#ffb347",
    fontWeight: "600",
  },

  timerBox: {
    backgroundColor: "rgba(255, 138, 29,0.15)",
    borderWidth: 1,
    borderColor: "#ff8a1d",
    padding: 10,
    borderRadius: 12,
    marginBottom: 10,
    alignItems: "center",
  },

  timerText: {
    color: "#ffb347",
    fontWeight: "600",
  },

  brand: {
    color: "#f2f2f2",
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  brandAccent: {
    color: "#ffb347",
  },
  subtitle: {
    marginTop: 6,
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "600",
  },
  headerRight: {
    alignItems: "flex-end",
    gap: 8,
  },
  pill: {
    minWidth: 84,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  pillValue: {
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "800",
  },
  pillLabel: {
    color: "#ffb347",
    fontSize: 11,
    fontWeight: "600",
  },
  levelBadge: {
    minWidth: 84,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#111113",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.25)",
  },
  levelBadgeText: {
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "800",
  },
  progressWrap: {
    marginBottom: 18,
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#ffb347",
  },
  progressLabel: {
    marginTop: 8,
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "600",
  },
  sectionCard: {
    padding: 18,
    borderRadius: 28,
    backgroundColor: "#111113",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.1)",
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.24,
    shadowRadius: 20,
    elevation: 5,
  },
  sectionCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  greeting: {
    color: "#f2f2f2",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 4,
  },
  sectionLead: {
    color: "#ffb347",
    fontSize: 13,
    fontWeight: "600",
  },
  phaseBadgeWrap: {
    alignItems: "flex-end",
  },
  phaseBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  phasePreflight: {
    backgroundColor: "rgba(255, 138, 29, 0.1)",
    borderColor: "rgba(255, 138, 29, 0.3)",
  },
  phaseAirborne: {
    backgroundColor: "rgba(255, 138, 29, 0.1)",
    borderColor: "rgba(255, 138, 29, 0.3)",
  },
  phaseLanding: {
    backgroundColor: "rgba(170, 170, 170, 0.1)",
    borderColor: "rgba(170, 170, 170, 0.3)",
  },
  phaseEmoji: {
    fontSize: 14,
  },
  phaseBadgeText: {
    color: "#f2f2f2",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  quote: {
    marginTop: 16,
    color: "#f2f2f2",
    fontSize: 17,
    lineHeight: 26,
    fontWeight: "600",
  },
  primaryButton: {
    alignSelf: "flex-start",
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: "#ffb347",
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: "#111113",
    fontSize: 13,
    fontWeight: "900",
  },
  secondaryButton: {
    marginTop: 16,
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  secondaryButtonText: {
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "800",
  },
  quickStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  statCard: {
    flex: 1,
    minWidth: 96,
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  statCardAmber: {
    paddingBottom: 12,
  },
  statCardGreen: {
    paddingBottom: 12,
  },
  statNumber: {
    color: "#f2f2f2",
    fontSize: 20,
    fontWeight: "900",
  },
  statLabel: {
    marginTop: 2,
    color: "#ffb347",
    fontSize: 10,
    fontWeight: "600",
    textTransform: "lowercase",
  },
  statTitleLabel: {
    color: "#ffb347",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  affirmationCard: {
    justifyContent: "flex-start",
    alignItems: "stretch",
  },
  affirmationLabel: {
    color: "#ffb347",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  affirmationText: {
    color: "#f2f2f2",
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 22,
    textAlign: "left",
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  sectionTitleIcon: {
    fontSize: 16,
  },
  sectionTitle: {
    color: "#f2f2f2",
    fontSize: 16,
    fontWeight: "800",
  },
  stageRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 8,
  },
  stageCard: {
    flex: 1,
    padding: 14,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.07)",
  },
  stageEmoji: {
    fontSize: 18,
    marginBottom: 8,
  },
  stageTitle: {
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 4,
  },
  stageDescription: {
    color: "#ffb347",
    fontSize: 11,
    lineHeight: 16,
  },
  stageAccent: {
    height: 3,
    borderRadius: 999,
    marginTop: 12,
    opacity: 0.9,
  },

  titleLabel: {
    color: "#ffb347",
    fontSize: 25,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginTop: 14,
    marginBottom: 6,
    textTransform: "uppercase",
  },

  label: {
    color: "#ffb347",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginTop: 14,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  dropdownGroup: {
    gap: 8,
  },
  dropdownButton: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  dropdownButtonActive: {
    borderColor: "#ffb347",
    backgroundColor: "rgba(255, 138, 29, 0.12)",
  },
  dropdownLabel: {
    color: "#ffb347",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dropdownValue: {
    marginTop: 4,
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "700",
  },
  dropdownMenu: {
    marginBottom: 4,
    padding: 8,
    borderRadius: 14,
    backgroundColor: "rgba(31, 31, 35, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  dropdownItemActive: {
    backgroundColor: "rgba(255, 138, 29, 0.12)",
  },
  dropdownItemText: {
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "600",
  },
  dropdownItemTextActive: {
    color: "#f2f2f2",
  },
  dropdownMenuRow: {
    flexDirection: "row",
    gap: 10,
    marginVertical: 10,
  },
  dropdownColumn: {
    flex: 1,
    backgroundColor: "rgba(31, 31, 35, 0.96)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
    overflow: "hidden",
  },
  dropdownColumnLabel: {
    color: "#ffb347",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 138, 29, 0.22)",
  },
  dropdownScrollView: {
    maxHeight: 180,
  },
  selectedTimeDisplay: {
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 8,
    textAlign: "center",
  },
  timeEncoderContainer: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    marginVertical: 10,
  },
  timeEncoder: {
    flex: 1,
    backgroundColor: "rgba(31, 31, 35, 0.96)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#f2f2f2",
    fontSize: 14,
    fontWeight: "600",
  },
  periodButton: {
    backgroundColor: "#ffb347",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 60,
    alignItems: "center",
  },
  periodButtonText: {
    color: "#111113",
    fontSize: 14,
    fontWeight: "700",
  },
  checkItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  checkItemDone: {
    backgroundColor: "rgba(170, 170, 170, 0.08)",
    borderColor: "rgba(170, 170, 170, 0.28)",
  },
  checkBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  checkBoxDone: {
    backgroundColor: "#f2f2f2",
    borderColor: "#f2f2f2",
  },
  checkTick: {
    color: "#111113",
    fontSize: 12,
    fontWeight: "900",
  },
  checkText: {
    flex: 1,
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "600",
  },
  checkEmoji: {
    fontSize: 16,
  },
  moodRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  moodButton: {
    minWidth: 42,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  moodButtonActive: {
    borderColor: "#ffb347",
    backgroundColor: "rgba(255, 138, 29, 0.12)",
  },
  moodText: {
    fontSize: 16,
  },
  inputRow: {
    flexDirection: "row",
    gap: 8,
  },
  input: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    color: "#f2f2f2",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  textArea: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  bodyText: {
    color: "#ffb347",
    fontSize: 13,
    lineHeight: 20,
  },
  landingFinalCard: {
    alignItems: "center",
  },
  landingFinalEmoji: {
    fontSize: 44,
    marginBottom: 10,
  },
  landingFinalTitle: {
    color: "#f2f2f2",
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 8,
  },
  statusRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: "rgba(170, 170, 170, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(170, 170, 170, 0.22)",
  },
  statusText: {
    color: "#f2f2f2",
    fontSize: 12,
    fontWeight: "700",
  },
  statusIcon: {
    fontSize: 18,
  },
  rewardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
    marginBottom: 8,
  },
  rewardCard: {
    width: "50%",
    padding: 6,
  },
  rewardCardUnlocked: {},
  rewardIcon: {
    fontSize: 28,
    marginBottom: 6,
  },
  rewardName: {
    color: "#f2f2f2",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  rewardReq: {
    color: "#ffb347",
    fontSize: 10,
  },
  optionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 8,
  },
  optionCard: {
    flexGrow: 1,
    flexBasis: "30%",
    minWidth: 96,
    padding: 12,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  optionCardActive: {
    backgroundColor: "rgba(255, 138, 29, 0.12)",
    borderColor: "rgba(255, 138, 29, 0.34)",
  },
  optionIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  colorSwatch: {
    width: 28,
    height: 28,
    borderRadius: 999,
    marginBottom: 8,
  },
  optionTitle: {
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "800",
  },
  optionHint: {
    color: "#ffb347",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 4,
  },
  manageCheckpointRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  removeButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "rgba(255, 59, 48, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(255, 59, 48, 0.32)",
  },
  removeButtonText: {
    color: "#ffb3ad",
    fontSize: 11,
    fontWeight: "900",
  },
  errorText: {
    color: "#ffb3ad",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 8,
  },
  achievementGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  achievementCard: {
    flex: 1,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  rewardRuleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  rewardValue: {
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "900",
  },
  locationGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  locationBadge: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "rgba(255, 138, 29, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.28)",
  },
  locationBadgeText: {
    color: "#f2f2f2",
    fontSize: 12,
    fontWeight: "800",
  },
  hangarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  hangarRowLocked: {
    opacity: 0.42,
  },
  hangarIcon: {
    fontSize: 22,
  },
  hangarName: {
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "700",
  },
  hangarReq: {
    color: "#ffb347",
    fontSize: 10,
    marginTop: 2,
  },
  emergencyButton: {
  backgroundColor: "#ff3b30",
  padding: 11,
  borderRadius: 12,
  alignItems: "center",
  marginBottom:40,
  shadowColor: "#e6554d",
  shadowOpacity: 0.4,
  shadowRadius: 8,
  elevation: 5,
},

emergencyButtonText: {
  color: "#fff",
  fontWeight: "700",
  },
  
  emergencyOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    backgroundColor: "rgba(31, 31, 35, 0.97)",
    justifyContent: "center",
    padding: 18,
  },
  emergencyCard: {
    borderRadius: 28,
    padding: 20,
    backgroundColor: "#111113",
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.24)",
  },
  emergencyTitle: {
    color: "#ff8a1d",
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 8,
  },
  emergencyText: {
    color: "#ffb347",
    fontSize: 13,
    lineHeight: 20,
  },
  emergencyToggleRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 16,
    marginBottom: 12,
  },
  emergencyToggle: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  emergencyToggleActive: {
    backgroundColor: "rgba(255, 138, 29, 0.12)",
    borderColor: "rgba(255, 138, 29, 0.3)",
  },
  emergencyToggleText: {
    color: "#ffb347",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  emergencyToggleTextActive: {
    color: "#ff8a1d",
  },
  emergencyPanel: {
    marginTop: 8,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  breatheTitle: {
    color: "#f2f2f2",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 6,
  },
  breatheText: {
    color: "#ffb347",
    fontSize: 13,
    lineHeight: 20,
  },
  groundingRow: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 6,
  },
  groundingStep: {
    color: "#ff8a1d",
    width: 18,
    fontSize: 12,
    fontWeight: "900",
  },
  groundingText: {
    flex: 1,
    color: "#ffb347",
    fontSize: 13,
    lineHeight: 18,
  },
  hotlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  hotlineIcon: {
    fontSize: 18,
  },
  hotlineName: {
    color: "#f2f2f2",
    fontSize: 13,
    fontWeight: "800",
  },
  hotlineNumber: {
    color: "#ffb347",
    fontSize: 11,
    marginTop: 2,
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 18,
    backgroundColor: "rgba(31, 31, 35, 0.94)",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderRadius: 18,
  },
  navItemActive: {
    backgroundColor: "rgba(255, 138, 29, 0.12)",
  },
  navIcon: {
    fontSize: 18,
    marginBottom: 4,
  },
  navLabel: {
    color: "#ffb347",
    fontSize: 10,
    fontWeight: "700",
  },
  navLabelActive: {
    color: "#f2f2f2",
  },
  pressed: {
    opacity: 0.85,
    transform: [{ scale: 0.99 }],
  },
  plane: {
    fontSize: 48,
    marginVertical: 20,
  },
  card: {
    backgroundColor: "rgba(31, 31, 35, 0.5)",
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
  },
  title: {
    fontSize: 16,
    fontWeight: "700",
    color: "#f2f2f2",
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  col: {
    flex: 1,
    backgroundColor: "rgba(31, 31, 35, 0.96)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
    maxHeight: 180,
  },
  item: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  selected: {
    color: "#ffb347",
    fontSize: 12,
    fontWeight: "600",
    marginVertical: 8,
    textAlign: "center",
  },
  dropdown: {
    backgroundColor: "rgba(31, 31, 35, 0.96)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  mood: {
    fontSize: 24,
    textAlign: "center",
  },
  takeoffBtn: {
    backgroundColor: "#ffb347",
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 12,
    alignItems: "center",
  },
  takeoffText: {
    color: "#111113",
    fontSize: 14,
    fontWeight: "700",
  },
  emergencyModal: {
    backgroundColor: "rgba(31, 31, 35, 0.95)",
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 138, 29, 0.22)",
  },
  timePickerContainer: {
  flexDirection: "row",
  justifyContent: "space-between",
  backgroundColor: "rgba(255,255,255,0.04)",
  borderRadius: 16,
  padding: 12,
  marginTop: 10,
},

timeColumn: {
  flex: 1,
  alignItems: "center",
},

timeColumnLabel: {
  fontSize: 12,
  opacity: 0.6,
  marginBottom: 6,
},

timeScroll: {
  height: 130,
  width: "100%",
},

timeItem: {
  height: 44,
  justifyContent: "center",
  alignItems: "center",
  borderRadius: 12,
},

timeItemActive: {
  backgroundColor: "rgba(255, 138, 29, 0.15)",
  transform: [{ scale: 1.05 }],
},

timeText: {
  fontSize: 18,
  opacity: 0.4,
},

timeTextActive: {
  opacity: 1,
  fontWeight: "700",
  color: "#ffb347",
},
});

export default styles;
