import { Link } from "react-router-dom";
import { LegalShell } from "@/components/shared/LegalShell";

const LAST_UPDATED = "June 2026";
const VERSION = "1.0.0";

interface Section {
  id: string;
  title: string;
  body: string[];
}

const SECTIONS: Section[] = [
  {
    id: "acceptance",
    title: "Accepting these terms",
    body: [
      "By creating an account, signing in, or otherwise using Mabuh-ai, you confirm that you have read, understood, and agreed to these Terms & Conditions and to the Privacy Policy. If you do not agree, please do not use the app.",
    ],
  },
  {
    id: "who-we-are",
    title: "Who we are",
    body: [
      "Mabuh-ai is a non-commercial, student-built wellbeing app created by BS Information Systems students at the College of Information and Communications Technology, West Visayas State University, as a class project for Mobile App Development. It is provided free of charge. We are not a healthcare provider and the team is made up of student developers, not licensed clinicians.",
    ],
  },
  {
    id: "not-medical-care",
    title: "Not a substitute for medical care",
    body: [
      "Mabuh-ai is a supportive tool for reflection and self-tracking. It does not provide medical advice, diagnosis, treatment, or therapy. If you are in crisis, having thoughts of self-harm, or believe you may be experiencing a mental-health condition, please contact a qualified professional or local emergency services. The app surfaces Philippine and Panay-region crisis hotlines in the Support tab, but it is not connected to emergency dispatch.",
    ],
  },
  {
    id: "ai-mistral-free",
    title: "AI companion and the free Mistral AI tier",
    body: [
      "The chat companion is powered by the free tier of Mistral AI. By using the companion you understand and agree that:",
      "The messages you send to the companion, and the replies you receive, may be transmitted to and processed by Mistral AI on infrastructure outside our control.",
      "On the free tier, Mistral may use these messages to train and improve their models. This is a condition of the free tier, not a setting we control.",
      "You should not share personal, sensitive, or identifying information (full name, address, phone number, school ID, account numbers, etc.) with the companion.",
      "Replies are generated by an AI and may be inaccurate or inappropriate. The companion is not a person. If a reply feels unhelpful or harmful, stop the conversation and reach out to a human via the Support tab.",
      "The AI companion is optional. You can use the rest of Mabuh-ai — check-ins, journal, journey, support resources — without ever talking to the companion.",
    ],
  },
  {
    id: "account",
    title: "Your account",
    body: [
      "You are responsible for keeping your sign-in credentials secure. Do not share your account.",
      "You agree to provide accurate information when you sign up and to keep it up to date.",
      "We may suspend or terminate accounts that violate these terms, abuse the service, or pose a safety risk to themselves or others.",
    ],
  },
  {
    id: "acceptable-use",
    title: "Acceptable use",
    body: [
      "Don't use Mabuh-ai to harass, threaten, or harm others.",
      "Don't try to reverse-engineer, scrape, or otherwise abuse the service or its AI features.",
      "Don't use the app to spread misinformation or to impersonate any person or organization.",
      "Don't enter content that is illegal, sexually explicit, or promotes self-harm in others.",
    ],
  },
  {
    id: "your-content",
    title: "Your content",
    body: [
      "You keep ownership of the check-ins, journal entries, and other content you create in Mabuh-ai.",
      "You grant us a limited, non-exclusive license to store and display that content back to you, and to use anonymized, aggregated insights from it to improve the app.",
      "As described above, content you send to the AI companion is also processed by Mistral AI under their free-tier terms.",
    ],
  },
  {
    id: "availability",
    title: "Availability and changes",
    body: [
      "Mabuh-ai is provided as-is. Because it is a student project, we cannot guarantee uninterrupted availability, and features may change, be added, or be removed as the app evolves.",
      "We may update these Terms & Conditions from time to time. Material changes will be announced in-app and on the login screen. The version number and last-updated date at the top of this document will always reflect the current version.",
    ],
  },
  {
    id: "no-warranty",
    title: "No warranty",
    body: [
      'Mabuh-ai is provided "as is" and "as available," without warranty of any kind, express or implied. We do not warrant that the app will be uninterrupted, error-free, or that any particular outcome will result from using it.',
    ],
  },
  {
    id: "limitation",
    title: "Limitation of liability",
    body: [
      "To the maximum extent permitted by law, the Mabuh-ai student team and West Visayas State University are not liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the app, including any reliance on AI-generated replies or any delay in seeking professional help.",
    ],
  },
  {
    id: "governing-law",
    title: "Governing law",
    body: ["These terms are governed by the laws of the Republic of the Philippines."],
  },
  {
    id: "contact",
    title: "Contact",
    body: [
      "Questions, concerns, or feedback: please reach out through the support channels listed in the app. We read every message.",
    ],
  },
];

export function TermsAndConditionsPage() {
  return (
    <LegalShell
      eyebrow="Legal"
      title="Terms & Conditions"
      lastUpdated={LAST_UPDATED}
      version={VERSION}
      agreementHref="/privacy"
    >
      <nav
        aria-label="Sections"
        className="rounded-2xl p-4"
        style={{
          background: "rgba(188,194,255,0.04)",
          border: "0.5px solid rgba(188,194,255,0.10)",
        }}
      >
        <p
          style={{
            fontSize: 11,
            letterSpacing: "0.18em",
            textTransform: "uppercase",
            color: "rgba(216,212,235,0.55)",
            margin: 0,
            marginBottom: 8,
          }}
        >
          On this page
        </p>
        <ul
          className="flex flex-col gap-1.5"
          style={{ listStyle: "none", padding: 0, margin: 0 }}
        >
          {SECTIONS.map((s) => (
            <li key={s.id}>
              <a
                href={`#${s.id}`}
                style={{
                  fontSize: 13,
                  color: "rgba(188,194,255,0.85)",
                  textDecoration: "none",
                }}
              >
                {s.title}
              </a>
            </li>
          ))}
        </ul>
      </nav>

      {SECTIONS.map((section) => (
        <section
          key={section.id}
          id={section.id}
          className="flex flex-col gap-2 scroll-mt-24"
        >
          <h2
            className="font-serif"
            style={{
              fontSize: 19,
              fontWeight: 500,
              color: "#eef1f6",
              letterSpacing: "-0.015em",
            }}
          >
            {section.title}
          </h2>
          {section.body.map((paragraph, i) => (
            <p
              key={i}
              style={{
                fontSize: 14,
                lineHeight: 1.65,
                color: "rgba(216,212,235,0.78)",
                margin: 0,
              }}
            >
              {paragraph}
            </p>
          ))}
        </section>
      ))}

      <section
        className="flex flex-col gap-2 rounded-2xl p-4"
        style={{
          background: "rgba(255,185,84,0.06)",
          border: "0.5px solid rgba(255,185,84,0.18)",
        }}
      >
        <h2
          className="font-serif"
          style={{
            fontSize: 17,
            fontWeight: 500,
            color: "#ffd99a",
            letterSpacing: "-0.01em",
          }}
        >
          Built by students
        </h2>
        <p
          style={{
            fontSize: 13.5,
            lineHeight: 1.6,
            color: "rgba(216,212,235,0.78)",
            margin: 0,
          }}
        >
          Mabuh-ai is a class project from BS Information Systems students at the College
          of Information and Communications Technology, West Visayas State University. It
          is free, non-commercial, and maintained as a learning project. Your feedback
          helps the team improve it for the next cohort of students.
        </p>
        <p style={{ fontSize: 13, margin: 0, marginTop: 6 }}>
          <Link
            to="/privacy"
            className="font-medium text-foreground underline decoration-[rgba(255,185,84,0.45)] underline-offset-4 transition-colors hover:decoration-foreground"
          >
            Read the Privacy Policy →
          </Link>
        </p>
      </section>
    </LegalShell>
  );
}

export default TermsAndConditionsPage;
